name: "Documentation-Review-Reminder"

on:
  schedule:
    # Schedule to run at 00:00 on the 1st day of January and July (every 6 months)
    - cron: '0 0 1 1,7 *'
  workflow_dispatch:

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create new documentation review issue
        run: |
          issue_body=$(cat .github/ISSUE_TEMPLATE/documentation_review.md)
          new_issue_url=$(gh issue create \
            --title "Documentation Review Reminder" \
            --label "documentation" \
            --body "$issue_body")
          echo "New issue created: $new_issue_url"
          echo "ISSUE_URL=$new_issue_url" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
